Repository log2timeline/plaso, pull requests merged in 2019-06, with the labels that each got.

#2593 Removed regvalue from USB device Windows Registry plugin #2566
  plaso/formatters/__init__.py
  plaso/formatters/usb.py
  plaso/parsers/winreg_plugins/usb.py
  tests/parsers/winreg_plugins/usb.py
Labels: to merge

#2579 Removed regvalue from MSIE zone settings Windows Registry plugin #2566
  plaso/formatters/__init__.py
  plaso/formatters/msie_zones.py
  plaso/parsers/winreg_plugins/msie_zones.py
  tests/parsers/winreg_plugins/msie_zones.py
Labels: to merge

#2611 Updated Sphinx configuration to 2.0.1 #2468
  docs/conf.py
  docs/requirements.txt
Labels: to merge

#2612 Removed regvalue from Winlogon Windows Registry plugin #2566
  plaso/formatters/__init__.py
  plaso/formatters/winlogon.py
  plaso/parsers/winreg_plugins/winlogon.py
  tests/parsers/winreg_plugins/winlogon.py
Labels: to merge

#2626 Removed regvalue from Windows drivers and services Registry plugins #2566
  plaso/analysis/windows_services.py
  plaso/containers/windows_events.py
  plaso/formatters/__init__.py
  plaso/formatters/services.py
  plaso/formatters/winregservice.py
  plaso/parsers/winreg_plugins/services.py
  tests/analysis/windows_services.py
  tests/containers/windows_events.py
  tests/formatters/services.py
  tests/parsers/winreg_plugins/services.py
Labels: to merge

#2573 Removed regvalue from default Windows Registry plugins #2566
  plaso/formatters/winreg.py
  plaso/parsers/winreg_plugins/default.py
  tests/parsers/winreg_plugins/terminal_server.py
Labels: to merge

#2591 Removed regvalue from typed URLs Windows Registry plugin #2566
  plaso/formatters/__init__.py
  plaso/formatters/typedurls.py
  plaso/parsers/winreg_plugins/typedurls.py
  tests/parsers/winreg_plugins/typedurls.py
Labels: to merge

#2587 Removed regvalue from timezone settings Windows Registry plugin and clean up #2566
  plaso/formatters/__init__.py
  plaso/formatters/timezone.py
  plaso/parsers/winreg_plugins/ccleaner.py
  plaso/parsers/winreg_plugins/timezone.py
  tests/parsers/winreg_plugins/ccleaner.py
  tests/parsers/winreg_plugins/timezone.py
Labels: to merge

#2615 Removed regvalue from Explorer ProgramCache Windows Registry plugins #2566
  plaso/containers/windows_events.py
  plaso/formatters/__init__.py
  plaso/formatters/programscache.py
  plaso/formatters/windows.py
  plaso/parsers/winreg_plugins/programscache.py
  tests/containers/windows_events.py
  tests/parsers/winreg_plugins/programscache.py
Labels: to merge

#2653 Replaced xml.etree by defusedxml #2652
  appveyor.yml
  config/dpkg/control
  config/linux/gift_copr_install.sh
  config/linux/gift_ppa_install.sh
  config/linux/gift_ppa_install_py3.sh
  config/macos/install.sh
  config/macos/make_dist.sh
  config/macos/uninstall.sh
  config/travis/install.sh
  config/travis/run_pylint.sh
  dependencies.ini
  plaso/dependencies.py
  plaso/output/kml.py
  plaso/parsers/android_app_usage.py
  plaso/parsers/czip_plugins/oxml.py
  plaso/parsers/opera.py
  plaso/parsers/plist_plugins/macuser.py
  requirements.txt
  setup.cfg
  tests/output/xlsx.py
Labels: code health

#2632 Unified _GetValuesFromKey function in Windows Registry plugins #2566
  plaso/formatters/winreg.py
  plaso/parsers/winreg_plugins/default.py
  plaso/parsers/winreg_plugins/interface.py
  plaso/parsers/winreg_plugins/lfu.py
  plaso/parsers/winreg_plugins/msie_zones.py
  plaso/parsers/winreg_plugins/programscache.py
  plaso/parsers/winreg_plugins/services.py
  plaso/parsers/winreg_plugins/windows_version.py
  tests/parsers/winreg_plugins/default.py
  tests/parsers/winreg_plugins/lfu.py
  tests/parsers/winreg_plugins/programscache.py
  tests/parsers/winreg_plugins/services.py
  tests/parsers/winreg_plugins/terminal_server.py
  tests/parsers/winreg_plugins/windows_version.py
Labels: code health

#2633 Added Windows Registry plugin interface tests #2566
  plaso/parsers/winreg_plugins/interface.py
  tests/parsers/winreg_plugins/interface.py
Labels: testing

#2651 Changes to extract EVTX TimeCreated #442
  plaso/parsers/winevtx.py
  tests/parsers/winevtx.py
Labels: enhancement, parsers

#2658 Changed ParseArguments to take sys.argv as argument #2024
  plaso/cli/image_export_tool.py
  plaso/cli/log2timeline_tool.py
  plaso/cli/pinfo_tool.py
  plaso/cli/psort_tool.py
  plaso/cli/psteal_tool.py
  test_data/psort_test.plaso
  tests/cli/image_export_tool.py
  tests/cli/log2timeline_tool.py
  tests/cli/pinfo_tool.py
  tests/cli/psort_tool.py
  tests/cli/psteal_tool.py
  tools/image_export.py
  tools/log2timeline.py
  tools/pinfo.py
  tools/psort.py
  tools/psteal.py
Labels: blocked, to merge

#2624 Changes to use dfVFS FindSpec location separator
  config/dpkg/control
  dependencies.ini
  plaso/dependencies.py
  plaso/engine/artifact_filters.py
  plaso/engine/engine.py
  plaso/engine/path_filters.py
  plaso/preprocessors/interface.py
  requirements.txt
  setup.cfg
  tests/engine/extractors.py
Labels: code health, to merge

#2564 Removed event filter DictObject helper #324
  plaso/filters/expression_parser.py
  plaso/filters/filters.py
  plaso/filters/helpers.py
  tests/filters/expression_parser.py
  tests/filters/helpers.py
Labels: code health

#2664 Renamed Fedora Core to Fedora in documentation
  docs/sources/developer/Dependencies-Fedora.md
  docs/sources/developer/Dependencies.md
  docs/sources/developer/Developers-Guide.md
  docs/sources/developer/Development-release-Fedora.md
  docs/sources/developer/Running-plaso-in-virtualenv.md
  docs/sources/user/Fedora-Packaged-Release.md
  docs/sources/user/Users-Guide.md
Labels: documentation
