Repository log2timeline/plaso, pull requests merged in 2020-06, with the labels that each got.

#2998 Code clean up of XSLX output module
  plaso/output/xlsx.py
Labels: code health, output

#2997 Updated pylint configuration
  .pylintrc
  test_dependencies.ini
Labels: code health

#3045 Updated MacOS Source release installation instructions
  docs/sources/user/MacOS-Source-Release.md
Labels: to merge

#3014 Removed backwards compatibilty for regvalue #2630
  config/pylint/spelling-private-dict
  plaso/formatters/winreg.py
  plaso/lib/definitions.py
  plaso/output/shared_elastic.py
  tests/storage/sqlite/merge_reader.py
Labels: code health

#3061 Added end-to-end configuration for CoreOS image #1981
  config/jenkins/linux/run_end_to_end_tests.sh
  config/jenkins/other/coreos.ini
Labels: to merge

#3041 Changes to tox configuration for uploading to codecov
  .pylintrc
  .travis.yml
  config/linux/ubuntu_install_plaso.sh
  config/travis/install.sh
  config/travis/run_coverage.sh
  config/travis/runtests.sh
  tox.ini
Labels: to merge

#3080 Moved timestamp event values string conversion into CreateEventFromValues
  tests/analysis/chrome_extension.py
  tests/analysis/file_hashes.py
  tests/analysis/nsrlsvr.py
  tests/analysis/sessionize.py
  tests/analysis/tagging.py
  tests/analysis/unique_domains_visited.py
  tests/analysis/viper.py
  tests/analysis/virustotal.py
  tests/containers/test_lib.py
  tests/filters/expression_parser.py
  tests/formatters/manager.py
  tests/output/dynamic.py
  tests/output/interface.py
  tests/output/json_line.py
  tests/output/json_out.py
  tests/output/kml.py
  tests/output/l2t_csv.py
  tests/output/mediator.py
  tests/output/null.py
  tests/output/rawpy.py
  tests/output/shared_elastic.py
  tests/output/shared_json.py
  tests/output/tln.py
  tests/output/xlsx.py
  tests/storage/sqlite/merge_reader.py
  tests/storage/test_lib.py
Labels: code health, testing

#3074 Moved timelib GetNow and GetCurrentYear into mediators #910
  plaso/analysis/mediator.py
  plaso/lib/timelib.py
  plaso/parsers/mediator.py
  plaso/parsers/pls_recall.py
  tests/parsers/mediator.py
Labels: to merge

#3092 Changes to make event values tests data driven #3042
  tests/parsers/test_lib.py
  tests/parsers/winprefetch.py
  tests/parsers/winrestore.py
  tests/parsers/xchatlog.py
  tests/parsers/xchatscrollback.py
  tests/parsers/zsh_extended_history.py
Labels: code health, testing

#3055 Updated profiling scripts and documentation
  docs/sources/developer/Profiling.md
  utils/plot_cpu_usage.py
  utils/plot_memory_usage.py
  utils/plot_task_queue.py
  utils/plot_tasks.py
Labels: to merge

#3076 Replaced instances of SemanticTime by subclasses
  config/dpkg/control
  config/dpkg/python-plaso.install
  dependencies.ini
  plaso/dependencies.py
  plaso/parsers/cookie_plugins/ganalytics.py
  plaso/parsers/esedb_plugins/file_history.py
  plaso/parsers/esedb_plugins/srum.py
  plaso/parsers/fseventsd.py
  plaso/parsers/msiecf.py
  plaso/parsers/ntfs.py
  plaso/parsers/olecf_plugins/automatic_destinations.py
  plaso/parsers/olecf_plugins/default.py
  plaso/parsers/opera.py
  plaso/parsers/plist_plugins/airport.py
  plaso/parsers/plist_plugins/launchd.py
  plaso/parsers/recycler.py
  plaso/parsers/safari_cookies.py
  plaso/parsers/winevt.py
  plaso/parsers/winevtx.py
  plaso/parsers/winlnk.py
  plaso/parsers/winprefetch.py
  plaso/parsers/winreg_plugins/appcompatcache.py
  plaso/parsers/winreg_plugins/officemru.py
  plaso/parsers/winreg_plugins/shutdown.py
  plaso/parsers/winreg_plugins/userassist.py
  plaso/parsers/winrestore.py
Labels: code health

#3015 Removed several outdated configuration files
  config/jenkins/windows/bootstrap-vm.ps1
  config/jenkins/windows/plaso_end_to_end_windows.ps1
  config/vagrant/Vagrantfile
  data/plaso_kibana_example.json
Labels: code health

#2946 Changes to storage for session configuration containers #109
  plaso/cli/log2timeline_tool.py
  plaso/cli/pinfo_tool.py
  plaso/cli/psort_tool.py
  plaso/cli/psteal_tool.py
  plaso/engine/knowledge_base.py
  plaso/engine/single_process.py
  plaso/multi_processing/psort.py
  plaso/multi_processing/task_engine.py
  plaso/storage/fake/writer.py
  plaso/storage/file_interface.py
  plaso/storage/interface.py
  plaso/storage/redis/writer.py
  tests/engine/knowledge_base.py
  tests/engine/single_process.py
  tests/multi_processing/psort.py
  tests/multi_processing/task_engine.py
  tests/output/test_lib.py
  tests/storage/sqlite/sqlite_file.py
Labels: to merge

#3078 Replaced timelib FromTimeString with dfDateTime #910
  config/dpkg/control
  config/travis/install.sh
  dependencies.ini
  plaso/dependencies.py
  plaso/lib/timelib.py
  plaso/parsers/java_idx.py
  requirements.txt
  setup.cfg
  tests/lib/timelib.py
Labels: to merge

#3100 Updated output time zone in the psort documentation #2894
  docs/sources/user/Using-psort.md
Labels: to merge

#3089 Unified test event formatters in formatters testlib #2524
  plaso/formatters/manager.py
  tests/formatters/manager.py
  tests/formatters/test_lib.py
  tests/multi_processing/psort.py
  tests/output/dynamic.py
  tests/output/json_line.py
  tests/output/json_out.py
  tests/output/l2t_csv.py
  tests/output/mediator.py
  tests/output/shared_json.py
  tests/output/test_lib.py
  tests/output/tln.py
  tests/output/xlsx.py
Labels: code health, testing

#3109 Added API documentation to release issue template
  .github/ISSUE_TEMPLATE/release.md
Labels: to merge

#3120 Cleaned up Sphinx configuration #3111
  docs/Makefile
  docs/conf.py
  docs/index.rst
  docs/make.bat
  docs/requirements.txt
Labels: to merge

#2971 Changes for psort to support EventDataStream #2956
  plaso/analysis/browser_search.py
  plaso/analysis/chrome_extension.py
  plaso/analysis/file_hashes.py
  plaso/analysis/interface.py
  plaso/analysis/sessionize.py
  plaso/analysis/tagging.py
  plaso/analysis/unique_domains_visited.py
  plaso/analysis/windows_services.py
  plaso/filters/event_filter.py
  plaso/filters/filters.py
  plaso/filters/interface.py
  plaso/multi_processing/analysis_process.py
  plaso/multi_processing/psort.py
  plaso/output/dynamic.py
  plaso/output/interface.py
  plaso/output/json_line.py
  plaso/output/json_out.py
  plaso/output/kml.py
  plaso/output/l2t_csv.py
  plaso/output/null.py
  plaso/output/rawpy.py
  plaso/output/shared_elastic.py
  plaso/output/shared_json.py
  plaso/output/tln.py
  plaso/output/xlsx.py
  tests/analysis/test_lib.py
  tests/cli/psort_tool.py
  tests/data/tag_linux.py
  tests/data/tag_macos.py
  tests/data/tag_windows.py
  tests/data/test_lib.py
  tests/filters/expression_parser.py
  tests/filters/filters.py
  tests/multi_processing/analysis_process.py
  tests/multi_processing/psort.py
  tests/output/dynamic.py
  tests/output/interface.py
  tests/output/json_line.py
  tests/output/json_out.py
  tests/output/kml.py
  tests/output/l2t_csv.py
  tests/output/manager.py
  tests/output/mediator.py
  tests/output/null.py
  tests/output/rawpy.py
  tests/output/shared_elastic.py
  tests/output/shared_json.py
  tests/output/test_lib.py
  tests/output/tln.py
  tests/output/xlsx.py
Labels: to merge

#2984 Changes to CreateEventFromValues test function for EventDataStream #2956
  plaso/analysis/interface.py
  plaso/output/l2t_csv.py
  plaso/output/rawpy.py
  plaso/output/shared_elastic.py
  plaso/output/shared_json.py
  tests/analysis/test_lib.py
  tests/containers/test_lib.py
  tests/filters/expression_parser.py
  tests/filters/filters.py
  tests/formatters/interface.py
  tests/formatters/manager.py
  tests/multi_processing/psort.py
  tests/output/dynamic.py
  tests/output/interface.py
  tests/output/json_line.py
  tests/output/json_out.py
  tests/output/kml.py
  tests/output/l2t_csv.py
  tests/output/mediator.py
  tests/output/null.py
  tests/output/rawpy.py
  tests/output/shared_elastic.py
  tests/output/shared_json.py
  tests/output/tln.py
  tests/output/xlsx.py
  tests/storage/event_heaps.py
  tests/storage/event_tag_index.py
  tests/storage/fake/writer.py
  tests/storage/redis/merge_reader.py
  tests/storage/redis/redis_store.py
  tests/storage/sqlite/merge_reader.py
  tests/storage/sqlite/sqlite_file.py
Labels: to merge

#2981 Moved path specification to EventDataStream #2956
  plaso/analysis/file_hashes.py
  plaso/analysis/interface.py
  plaso/analysis/nsrlsvr.py
  plaso/analysis/windows_services.py
  plaso/cli/pinfo_tool.py
  plaso/containers/events.py
  plaso/engine/worker.py
  plaso/formatters/default.py
  plaso/multi_processing/psort.py
  plaso/output/l2t_csv.py
  plaso/output/rawpy.py
  plaso/output/shared_elastic.py
  plaso/output/shared_json.py
  plaso/parsers/mediator.py
  tests/analysis/file_hashes.py
  tests/analysis/nsrlsvr.py
  tests/analysis/viper.py
  tests/analysis/virustotal.py
  tests/analysis/windows_services.py
  tests/containers/events.py
  tests/containers/test_lib.py
  tests/engine/worker.py
  tests/output/json_line.py
  tests/output/json_out.py
  tests/output/kml.py
  tests/output/null.py
  tests/output/rawpy.py
  tests/output/shared_json.py
  tests/output/tln.py
  tests/parsers/winreg_plugins/appcompatcache.py
  tests/parsers/winreg_plugins/bagmru.py
  tests/parsers/winreg_plugins/ccleaner.py
  tests/parsers/winreg_plugins/mountpoints.py
  tests/parsers/winreg_plugins/mrulistex.py
  tests/parsers/winreg_plugins/officemru.py
  tests/parsers/winreg_plugins/run.py
  tests/parsers/winreg_plugins/services.py
  tests/parsers/winreg_plugins/shutdown.py
  tests/parsers/winreg_plugins/typedurls.py
  tests/parsers/winreg_plugins/usb.py
  tests/parsers/winreg_plugins/usbstor.py
  tests/parsers/winreg_plugins/userassist.py
  tests/serializer/json_serializer.py
Labels: to merge

#2996 Added event formatting helper and changed l2t CSV to use DSV base class
  plaso/formatters/interface.py
  plaso/output/dynamic.py
  plaso/output/formatting_helper.py
  plaso/output/interface.py
  plaso/output/json_line.py
  plaso/output/json_out.py
  plaso/output/kml.py
  plaso/output/l2t_csv.py
  plaso/output/mediator.py
  plaso/output/rawpy.py
  plaso/output/shared_dsv.py
  plaso/output/shared_json.py
  plaso/output/tln.py
  tests/cli/psort_tool.py
  tests/cli/tool_options.py
  tests/multi_processing/psort.py
  tests/output/dynamic.py
  tests/output/formatting_helper.py
  tests/output/interface.py
  tests/output/l2t_csv.py
  tests/output/mediator.py
  tests/output/rawpy.py
  tests/output/shared_json.py
  tests/output/test_lib.py
Labels: to merge

#3021 Removed attributes from event data that can be derived from path spec
  plaso/analysis/mediator.py
  plaso/cli/extraction_tool.py
  plaso/cli/log2timeline_tool.py
  plaso/cli/psort_tool.py
  plaso/cli/psteal_tool.py
  plaso/containers/artifacts.py
  plaso/containers/sessions.py
  plaso/engine/configurations.py
  plaso/engine/engine.py
  plaso/engine/knowledge_base.py
  plaso/engine/single_process.py
  plaso/multi_processing/psort.py
  plaso/multi_processing/worker_process.py
  plaso/output/dynamic.py
  plaso/output/formatting_helper.py
  plaso/output/mediator.py
  plaso/parsers/filestat.py
  plaso/parsers/mediator.py
  plaso/parsers/ntfs.py
  test_data/end_to_end/extract_and_output.log
  test_data/end_to_end/extract_and_output_with_text_prepend.log
  tests/containers/artifacts.py
  tests/containers/sessions.py
  tests/engine/configurations.py
  tests/engine/knowledge_base.py
  tests/output/dynamic.py
  tests/output/mediator.py
  tests/parsers/mediator.py
Labels: to merge
