Repository log2timeline/plaso, pull requests merged in 2020-05, with the labels that each got.

#2932 Removed no longer needed py2to3 and changes for pylint
  docs/sources/api/plaso.lib.rst
  plaso/analysis/browser_search.py
  plaso/analysis/windows_services.py
  plaso/cli/helpers/interface.py
  plaso/cli/tools.py
  plaso/cli/views.py
  plaso/containers/events.py
  plaso/containers/interface.py
  plaso/engine/knowledge_base.py
  plaso/engine/path_helper.py
  plaso/filters/expressions.py
  plaso/filters/file_entry.py
  plaso/filters/filters.py
  plaso/filters/path_filter.py
  plaso/formatters/asl.py
  plaso/formatters/interface.py
  plaso/formatters/mediator.py
  plaso/formatters/olecf.py
  plaso/lib/loggers.py
  plaso/lib/py2to3.py
  plaso/multi_processing/psort.py
  plaso/output/dynamic.py
  plaso/output/l2t_csv.py
  plaso/output/manager.py
  plaso/output/rawpy.py
  plaso/output/shared_elastic.py
  plaso/output/shared_json.py
  plaso/output/tln.py
  plaso/output/xlsx.py
  plaso/parsers/cookie_plugins/ganalytics.py
  plaso/parsers/czip_plugins/oxml.py
  plaso/parsers/dsv_parser.py
  plaso/parsers/esedb_plugins/msie_webcache.py
  plaso/parsers/mediator.py
  plaso/parsers/olecf_plugins/summary.py
  plaso/parsers/popcontest.py
  plaso/parsers/sqlite_plugins/android_calls.py
  plaso/parsers/sqlite_plugins/mac_notes.py
  plaso/parsers/sqlite_plugins/mackeeper_cache.py
  plaso/parsers/text_parser.py
  plaso/parsers/trendmicroav.py
  plaso/parsers/winevtx.py
  plaso/preprocessors/windows.py
  plaso/serializer/json_serializer.py
  tests/cli/helpers/event_filters.py
  tests/engine/artifact_filters.py
  tests/parsers/sqlite.py
Labels: code health

#2928 Changes to list output modules alphabetically
  plaso/cli/tool_options.py
Labels: UX, tools

#2933 Additions to tag_linux.txt
  data/tag_linux.txt
  tests/data/tag_linux.py
Labels: analysis, enhancement

#2935 Changes to have DSV parser detect byte-order-marks and clean up #2919
  plaso/parsers/dsv_parser.py
  plaso/parsers/mactime.py
  plaso/parsers/mcafeeav.py
  plaso/parsers/networkminer.py
  plaso/parsers/trendmicroav.py
  tests/parsers/apache_access.py
  tests/parsers/dsv_parser.py
  tests/parsers/santa.py
Labels: code health, enhancement, parsers

#2949 Corrected errors in end-to-end test configurations
  config/jenkins/greendale/psort-dean-hashes.ini
  config/jenkins/greendale/psort-studentpc1-services.ini
  config/jenkins/greendale/psort-studentpc1-sessionize-unique-domains.ini
  config/jenkins/greendale/psort-studentpc1-tagging.ini
Labels: testing

#2944 Changed docstrings to be consistent with rest of codebase
  plaso/parsers/syslog.py
  plaso/parsers/syslog_plugins/interface.py
Labels: code health

#2962 Changes to formatting strings for type()
  plaso/containers/events.py
  plaso/engine/artifact_filters.py
  plaso/multi_processing/analysis_process.py
  plaso/multi_processing/worker_process.py
  plaso/serializer/json_serializer.py
  plaso/storage/fake/writer.py
  plaso/storage/sqlite/sqlite_file.py
  tests/analysis/test_lib.py
  tests/parsers/test_lib.py
Labels: code health

#2963 Removed redundant calls to iter()
  plaso/analysis/browser_search.py
  plaso/analysis/manager.py
  plaso/analysis/tagging.py
  plaso/analysis/viper.py
  plaso/analyzers/hashers/manager.py
  plaso/analyzers/manager.py
  plaso/cli/psort_tool.py
  plaso/cli/psteal_tool.py
  plaso/containers/interface.py
  plaso/engine/knowledge_base.py
  plaso/formatters/interface.py
  plaso/formatters/olecf.py
  plaso/formatters/safari_cookies.py
  plaso/multi_processing/engine.py
  plaso/multi_processing/task_manager.py
  plaso/output/manager.py
  plaso/parsers/bencode_plugins/interface.py
  plaso/parsers/bencode_plugins/utorrent.py
  plaso/parsers/chrome_cache.py
  plaso/parsers/cookie_plugins/ganalytics.py
  plaso/parsers/cookie_plugins/manager.py
  plaso/parsers/cups_ipp.py
  plaso/parsers/iis.py
  plaso/parsers/interface.py
  plaso/parsers/mactime.py
  plaso/parsers/manager.py
  plaso/parsers/mediator.py
  plaso/parsers/msiecf.py
  plaso/parsers/olecf_plugins/summary.py
  plaso/parsers/plist_plugins/appleaccount.py
  plaso/parsers/plist_plugins/bluetooth.py
  plaso/parsers/plist_plugins/interface.py
  plaso/parsers/plist_plugins/ipod.py
  plaso/parsers/plist_plugins/macuser.py
  plaso/parsers/plist_plugins/spotlight.py
  plaso/parsers/plist_plugins/spotlight_volume.py
  plaso/parsers/sqlite_plugins/mackeeper_cache.py
  plaso/parsers/syslog_plugins/interface.py
  plaso/parsers/winreg.py
  plaso/parsers/winreg_plugins/bagmru.py
  plaso/preprocessors/macos.py
  plaso/serializer/json_serializer.py
  tests/analysis/test_lib.py
  tests/engine/worker.py
  tests/multi_processing/test_lib.py
  tests/parsers/manager.py
  tests/parsers/test_lib.py
Labels: code health

#2938 Changes to make tagging file tests data driven #2937
  tests/data/tag_linux.py
  tests/data/tag_macos.py
  tests/data/tag_windows.py
  tests/data/test_lib.py
Labels: testing

#2958 Removed GZIP storage identifiers from event attribute containers
  plaso/containers/events.py
  tests/containers/events.py
  tests/containers/time_events.py
Labels: code health

#2947 Changes for Elasticseach 6 end-to-end tests #2931
  config/jenkins/linux/run_end_to_end_tests.sh
  config/jenkins/linux/run_end_to_end_tests_py3.sh
  config/linux/ubuntu_install_elasticsearch6.sh
  config/linux/ubuntu_install_elasticsearch7.sh
  config/linux/ubuntu_install_plaso.sh
Labels: testing

#2941 Changed pylint CI test to Ubuntu 20.04
  .travis.yml
  config/travis/install.sh
  config/travis/run_pylint.sh
  plaso/cli/helpers/analysis_plugins.py
  plaso/cli/helpers/data_location.py
  plaso/cli/helpers/date_filters.py
  plaso/cli/helpers/output_modules.py
  plaso/cli/helpers/profiling.py
  plaso/cli/helpers/temporary_directory.py
  plaso/parsers/apt_history.py
  plaso/parsers/bencode_plugins/interface.py
  plaso/parsers/czip_plugins/interface.py
  plaso/parsers/docker.py
  plaso/parsers/firefox_cache.py
  plaso/parsers/fseventsd.py
  plaso/parsers/plist_plugins/interface.py
  plaso/parsers/safari_cookies.py
  plaso/parsers/utmp.py
  plaso/parsers/utmpx.py
  plaso/parsers/winlnk.py
  plaso/parsers/winreg_plugins/interface.py
  plaso/parsers/winreg_plugins/lfu.py
  plaso/parsers/winreg_plugins/officemru.py
  setup.py
Labels: code health, to merge

#2959 Replaced deprecated methods in psteal tests
  tests/cli/psteal_tool.py
Labels: code health

#2948 Added end-to-end test configuration for output to Elasticsearch with raw fields
  config/jenkins/greendale/output_elastic_with_raw_fields.ini
Labels: testing

#2954 Added end-to-end test configuration for output to Timesketch
  config/jenkins/greendale/output_timesketch.ini
  config/linux/ubuntu_install_timesketch.sh
Labels: testing

#2980 Removed Python 2 code from analysis interface
  plaso/analysis/interface.py
Labels: code health

#2799 Initial implementation of redis task store (#2388)
  appveyor.yml
  config/dpkg/control
  config/jenkins/greendale/studentpc1-redis.ini
  config/linux/gift_copr_install.sh
  config/linux/ubuntu_install_plaso.sh
  config/travis/install.sh
  dependencies.ini
  plaso/cli/helpers/storage_format.py
  plaso/dependencies.py
  plaso/lib/definitions.py
  plaso/multi_processing/task_engine.py
  plaso/multi_processing/task_manager.py
  plaso/storage/factory.py
  plaso/storage/fake/writer.py
  plaso/storage/file_interface.py
  plaso/storage/identifiers.py
  plaso/storage/interface.py
  plaso/storage/redis/__init__.py
  plaso/storage/redis/merge_reader.py
  plaso/storage/redis/reader.py
  plaso/storage/redis/redis_store.py
  plaso/storage/redis/writer.py
  plaso/storage/sqlite/merge_reader.py
  plaso/storage/sqlite/sqlite_file.py
  plaso/storage/sqlite/writer.py
  requirements.txt
  setup.cfg
  test_dependencies.ini
  test_requirements.txt
  tests/cli/helpers/storage_format.py
  tests/storage/redis/__init__.py
  tests/storage/redis/merge_reader.py
  tests/storage/redis/redis_store.py
Labels: to merge
